### ISSUE TITLE
[Feature Request] Enabling override of builder props

### ISSUE THREAD

**Issue by morsh** [Vincent-Pang/builder-pattern#25]
Hi,
In our projects we usually use builders like this for usage in tests:

contact-builder.ts
```ts
export const aContact = () => Builder<Contact>().fullName(chance.string()).phoneNumber(chance.phone()).build();
```
This is done so that not every test needs to know "Builder" and "Contact" and "<template>" to function.

The thing is that many tests, want to add an override on the default properties. So we end up writing the builders like so:

```ts
export const aContact = (props?: Partial<Contact>) => ({
  ...Builder<Contact>().fullName(chance.string()).phoneNumber(chance.phone()).build(),
  ...props,
});
```

**Feature Request**
Being able to call an "override" method before calling build (which is like calling the constructor):
```ts
export const aContact = (props?: Partial<Contact>) =>
  Builder<Contact>()
    .fullName(chance.string())
    .phoneNumber(chance.phone())
    .override(props)
    .build();
```
Or simply use the build method:
```ts
export const aContact = (props?: Partial<Contact>) =>
  Builder<Contact>()
    .fullName(chance.string())
    .phoneNumber(chance.phone())
    .build(props);
```

I'm willing to donate the code, just want to know the feature will be accepted.

**Comment by Vincent-Pang** [comment]
Hi,

I added this feature in v2.2.0.

You may call like this
```typescript
export const aContact = (props?: Partial<Contact>) =>
  Builder<Contact>(null, props)
    .fullName(chance.string())
    .phoneNumber(chance.phone())
    .build();
```

I implemented .override() (a train function) like your proposed method at first, but a few moments later I think it is better "occupy" the parameter name as less as possible. i.e. if .override() was used, then users cannot have their POJO containing a variable named "override".

Moreover, I think it is similar to another "template object" feature, so I choose to pass the parameter in the constructor rather than in the build().

**Comment by morsh** [comment]
Oh, I totally missed that part in the documentation. Thanks!
