### ISSUE TITLE
Performance of the lib compared to vanilla Javascript

### ISSUE THREAD

**Issue by tosun-si** [Vincent-Pang/builder-pattern#4]
Vincent Peng, your open source lib for the builder pattern is a very good idea, thanks.

I have a question about performance.
I sometimes read that the ES6 proxies are not very fast and performant compared to the vanilla javascript.

If we use your lib, the performance are good ?
Can you give me an opinion about that please ?

Sorry to open an issue for that, but i wanted to send you a private message, but i didn't find your email address.

**Comment by Vincent-Pang** [comment]
Hi, thank you for your question. I have just made a simple test to the library, [test program](https://github.com/Vincent-Pang/builder-pattern-performance-test/blob/master/src/main.ts), the performace is not as good as vanilla javascript. In my opinion, I am still willing to use this lib because I believe that the performace impact is small when comparing to the whole program. Of course if the path is critical or hot, it is reasonable to use vanilla approach.
